#pragma once

/***************** Cocos Scene or Atlas folder names **************************/
#define COCOS_FOLDER_COMMON						"Common/"
#define COCOS_FOLDER_SCENE_BATTLES				"Scene_Battles/"
#define COCOS_FOLDER_SCENE_BONUSBLITZ			"Scene_BonusBlitz/"
#define COCOS_FOLDER_SCENE_COVERFLOW			"Scene_CoverFlow/"
#define COCOS_FOLDER_FTUE						"Scene_FTUE/"
#define COCOS_FOLDER_SCENE_POWERUPSELECTION		"Scene_PowerUpSelection/"
#define COCOS_FOLDER_SCENE_SPLASH				"Scene_Splash/"
#define COCOS_FOLDER_SCENE_STORE				"Scene_Store/"
#define COCOS_FOLDER_SCENE_WRAPSCREEN			"Scene_WrapScreen/"
#define COCOS_FOLDER_SCENE_TOURNAMENTS			"Scene_Tournaments/"
#define COCOS_FOLDER_SCENE_ACTIVITIES			"Scene_Activities/"
/***************** Cocos Scene or Atlas folder names **************************/

/*****************************For Holiday Tournament**************************/

#define HOLIDAY_TOURNAMENT						"HolidayTournament_Menu/"
/******************************************************************************/


/* All popup view names*/
#define POPUP_PU_WEEKLYUNLOCK					"PopUp_PowerUpWeeklyUnlock"
#define POPUP_PU_INFO							"PopUp_PowerUpInfo"
#define POPUP_BONUSBLITZ_CLAIM					"Popup_BonusBlitzClaim"
#define POPUP_BONUSBLITZ_INFO					"Popup_BonusBlitzInfo"
#define POPUP_PU_NOPOWERUPS						"Popup_NoPowerUps"
#define POPUP_NEEDMORECOINS						"Popup_NeedMoreCoins"
#define POPUP_MINIMENU							"Popup_CoverFlowMiniMenu"
#define POPUP_GENERIC		   					"Popup_SceneGeneric"
#define POPUP_TOURNAMENT_INFO					"Popup_TournamentInfo"
#define POPUP_BATTLES_DEBUG						"Popup_CocosSceneBattleDebugMenu"
#define POPUP_LEVEL_UP							"Popup_LevelUp"
#define POPUP_NEXT_LEVEL						"Popup_NextLevel"
#define	POPUP_TOUNNAMENT_CLAIM_SHARE			"Popup_TournamentClaimShare"
#define POPUP_DBQ_CLAIM							"Popup_DBQClaim"
#define POPUP_ACHIEVEMENT_TOAST					"Popup_AchievementToast"
#define POPUP_MYSTERBOX_INFO					"Popup_MysteryBoxInfo"
#define POPUP_WEEKLY_LEADERBOARD				"Popup_SinglePlayerResetLeaderboard"
#define POPUP_LEADERBOARD_MYSTERYBOX_REWARD		"Popup_LeaderboardMysteryBoxClaim"
#define POPUP_SOCIAL							"Popup_Social"
#define POPUP_SP_LEADRBOARD_MYSTERYBOX_INFO		"Popup_SpLeaderboardMysteryboxInfo"
#define POPUP_POTW_UNLOCK						"Popup_POTW"
#define POPUP_GENERIC_SMALL						"Popup_GenericSmall"
#define POPUP_POWERUP_UNLOCK					"Popup_PowerupUnlock"
#define POPUP_STORE_BUNDLE_INFO					"Popup_StoreBundleInfo"
#define POPUP_FORCE_UPDATE						"Popup_ForceUpdate"
#define POPUP_WHATSNEW							"Popup_WhatsNew"
#define POPUP_PAUSEMENU							"Popup_PauseMenu"
#define POPUP_TOURNAMENT_TIE_BREAKER			"Popup_TournamentTieBreaker"
#define POPUP_GENERIC_REWARDS					"Popup_GenericRewards"
#define POPUP_WEBVIEW				            "Popup_WebView"
#define POPUP_SOCIAL_REWARD						"Popup_SocialRewardClaim"
#define POPUP_GLOBAL_REWARD						"Popup_GlobalRewardClaim"
#define POPUP_UPSIGHT_REWARD					"Popup_UpsightRewardClaim"
#define POPUP_INVENTORY_REWARD					"Popup_InventoryRewardClaim"
#define POPUP_DAILYACTIVITY_REWARD				"Popup_DailyActivityRewards"
/* All popup view names */

/* All  view names*/
#define VIEW_LOADING							"Loading"
#define VIEW_SPLASH								"SplashView"
#define VIEW_BG									"BG"
#define VIEW_COVERFLOW							"CoverFlow"
#define VIEW_BONUSBLITZBOARD					"BonusBlitzBoard"
#define VIEW_HELPABOUT							"CoverFlowHelpAbout"
#define VIEW_EDITPROFILE						"CoverFlowEditProfile"
#define VIEW_PUSELECTION						"PUSelection"
#define VIEW_SHOPVIEW							"ShopView"
#define VIEW_WRAPSCREEN_SINGLEPLAYER			"WrapScreenSingleplayer"
#define VIEW_WRAPSCREEN_GOLDRUSH				"WrapScreenGoldRush"
#define VIEW_WRAPSCREEN_TOURNAMENTS				"WrapScreenTournaments"
#define VIEW_WRAPSCREEN_DAILYCHALLENGE			"WrapScreenDailyChallenge"
#define VIEW_WRAPSCREEN_BATTLES					"WrapScreenBattles"
#define VIEW_GAME								"CocosSceneGame"
#define VIEW_LANGUAGESELECTION					"CocosSceneLanguageSelection"
#define VIEW_CHEATMENU							"CocosSceneCheatMenu"
#define VIEW_BATTLESLOBBY						"CocosSceneBattlesLobby"
#define VIEW_ACHIEVEMENTS						"CocosSceneAchievements"
#define VIEW_BATTLESLEADERBOARD					"CocosSceneBattlesLeaderboard"
#define VIEW_TOURNAMENTSLOBBY					"Cocos_Scene_Tournaments"
#define VIEW_TOURNAMENTSSTANDINGS				"TournamentsStandings"
#define VIEW_TIERINFO							"BattlesTierInfo"
#define VIEW_FTUE								"FTUE"
#define VIEW_INBOX								"CocosSceneMessages"
#define VIEW_DEBUG_MENU							"CocosDebugMenu"
#define VIEW_DAILYACTIVITIESLOBBY				"Cocos_Scene_Activities"

/* All  view names */
